# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b812d155a7e86ac5ec30d7bb027fc49d370fe0361ac74585845eb3e4ffb3ace176d8f3f930ab4ff62099405c83c03030fd54fc3ae80f24aa6dde45eefce233ea

test:
  secret_key_base: b30654a163bc95513a268e8494a4f0a16fed3836b8a5eafae1ef8ebfa920dd6db8ed480a43ce87fa1b6ca987b84c4185a8859dda6e2e65c846bf4d07bc788b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
